steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - '--no-cache'
          - '-t'
          - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME'
          - ui
          - '-f'
          - ui/Dockerfile
      id: Build
images:
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_IMAGE_NAME'
timeout: 900s
options:
    substitutionOption: ALLOW_LOOSE
tags:
    - apellum-ui
